openapi: 3.0.0
info:
  title: Crypto Market Data API
  description: This is a simple API for getting crypto market data
  version: 1.0.0
  contact:
    name: XXX
servers:
  - description: Production
    url: "xxx"
paths:
  /v1/crypto/trade:
    $ref: ./paths/crypto/trade.yaml
components:
  parameters:
    Symbol:
      $ref: ./parameters/crypto/symbol.yaml
  schemas:
    Trade:
      $ref: ./schemas/crypto/trade.yaml
